// flow-typed signature: 12c4f4c0f24dee87f34091de5c24014a
// flow-typed version: <<STUB>>/atom_v1.20.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom' {
  declare module.exports: any;
}

declare var atom: any;
